server.port: ${SERVER_PORT:7000}
spring:
  application:
    name: hello


management.endpoints.web.exposure.include: "*"
# management.endpoints.web.exposure.include: health,info,prometheus
management.endpoint.health.show-details: always
management.metrics.tags.application: hello-api, hello-ui, hello-api-svc, hello-ui-svc
management.prometheus.metrics.export.enabled: true


