datadog:
  apiKey: cff5b1a2d1aaac00c29a4294e63a0915
  clusterName: saravanjs
  hostname: k8master

  clusterAgent:
    enabled: true
    metricsProvider:
      enabled: true
    env:
      - name: DD_CLUSTER_NAME
        value: saravanjs

  env:
    - name: DD_HOSTNAME
      value: k8master
    - name: DD_CLUSTER_NAME
      value: saravanjs

  logs:
    enabled: true
    containerCollectAll: true